name: example
description: A project that showcases usage of omega_dio_logger
publish_to: none
environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.3.0
  flutter:
    sdk: flutter
  omega_dio_logger:
    path:
      ../

dev_dependencies:
  carapacik_lints: ^1.4.2
