name: example
description: A project that showcases usage of omega_dio_logger
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dio: ^5.2.0
  flutter:
    sdk: flutter
  omega_dio_logger: ^1.2.1

dev_dependencies:
  carapacik_lints: ^1.3.2
