name: example
description: A project that showcases usage of omega_dio_logger
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  dio: ^5.0.0
  flutter:
    sdk: flutter
  omega_dio_logger:
    path:
      ../
