name: omega_dio_logger
description: Dio interceptor that logs network calls in a pretty, easy to read format with curl command
version: 1.0.2
repository: https://github.com/Omega-R/omega_dio_logger
homepage: https://omega-r.com
environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: ^5.0.1

dev_dependencies:
  carapacik_lints: ^1.0.7
