name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk:
          - stable
          - 2.19.6
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: subosito/flutter-action@v2.10.0
        with:
          sdk: "${{ matrix.sdk }}"
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: dart format --set-exit-if-changed -o none .
      - name: Analyze
        run: dart analyze lib
