name: analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Analyze"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk:
          - stable
          - 2.18.7
          - 2.17.7
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: dart-lang/setup-dart@v1.4
        with:
          sdk: "${{ matrix.sdk }}"
      - name: Install dependencies
        run: dart pub get
      - name: Format
        run: dart format --set-exit-if-changed -o none .
      - name: Analyze
        run: dart analyze
