name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk:
          - stable
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: dart-lang/setup-dart@v1.5.0
        with:
          sdk: "${{ matrix.sdk }}"
      - name: Install dependencies
        run: dart pub get
      - name: Format
        run: dart format --set-exit-if-changed -o none .
      - name: Analyze
        run: dart analyze lib
